#!/bin/busybox sh

echo "[info] Mount devices"
mount -t devtmpfs  devtmpfs  /dev
mount -t proc      proc      /proc
mount -t sysfs     sysfs     /sys
mount -t tmpfs     tmpfs     /tmp

echo "[debug] ls /"
ls /
echo "[debug] ls /bin"
ls /bin

# Busybox TTY fix
echo "[info] Launch shell"
# setsid cttyhack sh
setsid sh -c 'sh </dev/hvc0 >/dev/hvc0 2>&1'

# # https://git.busybox.net/busybox/tree/docs/mdev.txt?h=1_32_stable
# echo /sbin/mdev > /proc/sys/kernel/hotplug
# mdev -s

poweroff -f
