#!/bin/busybox sh

# Make symlinks
/bin/busybox echo "[info] Create busybox symlinks"
/bin/busybox --install -s

echo "[info] Mount devices"
mount -t devtmpfs  devtmpfs  /dev
mount -t proc      proc      /proc
mount -t sysfs     sysfs     /sys
mount -t tmpfs     tmpfs     /tmp

# Busybox TTY fix
echo "[info] Launch shell"
setsid cttyhack sh

# # https://git.busybox.net/busybox/tree/docs/mdev.txt?h=1_32_stable
# echo /sbin/mdev > /proc/sys/kernel/hotplug
# mdev -s

# sh

poweroff -f
