name: Build xvisor

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/defermelowie/riscv-hext-ci-env/toolchain:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install build dependencies
      run: apt-get install cpio bison flex bc device-tree-compiler -y

    - name: Setup directory structure
      run: make setup

    - name: Build xvisor
      run: make -f xvisor.mk build CROSS_COMPILE=riscv64-linux-gnu-

    - name: Archive xvisor blobs
      uses: actions/upload-artifact@v4
      with:
        path: ./target/**
