name: Build & run linux

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/defermelowie/riscv-hext-ci-env/toolchain:v1.0.5
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install build dependencies
        run: apt-get install cpio bison flex bc device-tree-compiler -y

      - name: Setup directory structure
        run: make setup

      - name: Build linux
        run: make -f linux.mk build CROSS_COMPILE=riscv64-linux-gnu-

      - name: Archive linux binaries
        uses: actions/upload-artifact@v4
        with:
          name: linux-binaries
          path: |
            ./target/opensbi_linux_payload.elf
            ./target/rv64gch_linux.dtb
          if-no-files-found: error

  run-spike:

    needs: build-linux
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/defermelowie/riscv-hext-ci-env/spike:v1.0.5
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
      - name: Download linux binaries
        uses: actions/download-artifact@v4
        with:
          name: linux-binaries

      - name: Run on spike
        run: echo "exit" | spike --isa rv64gcvh_zbb_zicsr -m512 --dtb=rv64gch_linux.dtb opensbi_linux_payload.elf

  run-csim:

    needs: build-linux
    runs-on: ubuntu-latest

    steps:
      - name: Build csim
        run: echo "[TODO] Build csim"

      - name: Download linux binaries
        uses: actions/download-artifact@v4
        with:
          name: linux-binaries

      - name: Run on csim
        run: echo "[TODO] Run linux on csim"
