name: Build & run linux

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/defermelowie/riscv-hext-ci-env/toolchain:v1.0.5
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install build dependencies
        run: apt-get install cpio bison flex bc device-tree-compiler -y

      - name: Setup directory structure
        run: make setup

      - name: Build linux
        run: make -f linux.mk build CROSS_COMPILE=riscv64-linux-gnu-

      - name: Archive linux binaries
        uses: actions/upload-artifact@v4
        with:
          name: linux-binaries
          path: |
            ./target/opensbi_linux_payload.elf
            ./target/rv64gch_linux.dtb
          if-no-files-found: error

  build-sim:

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get install zlib1g-dev pkg-config libgmp-dev z3 -y

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup ocaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "5.1"

      - name: Install sail
        run: |
          opam init --disable-sandboxing -y
          opam install sail -y

      - name: Build sail emulators
        run: |
          eval $(opam env)
          cd sim/sail
          make csim ARCH=RV64
          make osim ARCH=RV64

      - name: Archive emulator binaries
        uses: actions/upload-artifact@v4
        with:
          name: sail-emulators
          path: |
            sim/sail/c_emulator/riscv_sim_RV64
            sim/sail/ocaml_emulator/riscv_ocaml_sim_RV64

  run-spike:

    needs: build-linux
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/defermelowie/riscv-hext-ci-env/spike:v1.0.5
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
      - name: Download linux binaries
        uses: actions/download-artifact@v4
        with:
          name: linux-binaries

      - name: Run on spike
        run: spike --isa rv64gcvh_zbb_zicsr -m512 --dtb=rv64gch_linux.dtb opensbi_linux_payload.elf

  run-csim:

    needs: [build-linux, build-sim]
    runs-on: ubuntu-latest

    steps:
      - name: Download emulator binaries
        uses: actions/download-artifact@v4
        with:
          name: sail-emulators

      - name: Download linux binaries
        uses: actions/download-artifact@v4
        with:
          name: linux-binaries
      - run: chmod +x c_emulator/riscv_sim_RV64 & chmod +x ocaml_emulator/riscv_ocaml_sim_RV64

      - name: Run on csim
        run: >
          c_emulator/riscv_sim_RV64 -Vmem -Vplatform -Vreg -Vinstr
          --enable-dirty-update --enable-pmp --mtval-has-illegal-inst-bits --xtinst-has-transformed-inst
          --ram-size 512 --device-tree-blob rv64gch_linux.dtb opensbi_linux_payload.elf
