name: Build & run xvisor

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-xvisor:

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/defermelowie/riscv-hext-ci-env/toolchain:v1.0.5
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install build dependencies
      run: apt-get install cpio bison flex bc device-tree-compiler -y

    - name: Setup directory structure
      run: make setup

    - name: Build xvisor
      run: make -f xvisor.mk build CROSS_COMPILE=riscv64-linux-gnu-

    - name: Archive xvisor binaries
      uses: actions/upload-artifact@v4
      with:
        name: xvisor-binaries
        path: |
          ./target/opensbi_xvisor_payload.elf
          ./target/rv64gch_xvisor.dtb
        if-no-files-found: error

  run-spike:
    needs: build-xvisor
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/defermelowie/riscv-hext-ci-env/spike:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
      - name: Download xvisor elf
        uses: actions/download-artifact@v4
        with:
          name: xvisor-binaries

      - name: Run on spike
        run: echo "autoexec" | spike --isa rv64gcvh_zbb_zicsr -m1024 --dtb=rv64gch_xvisor.dtb opensbi_xvisor_payload.elf
        timeout-minutes: 10
